FROM maven:3.3.3-openjdk-21  AS  build
COPY . .
RUN mvn clean package -DskipTests

FROM openjdk:21.0.1-jdk-slim
COPY --from=build /target/assignmentDemo-0.0.1-SNAPSHOT.jar assignmentDemo.jar
EXPOSE 8080
ENTRYPOINT [ "java","-jar","assignmentDemo.jar" ]